name: Testing for push
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run compile
      - name: Install pm2
        run: npm install pm2@latest -g
      - name: Start pm2
        run: pm2 start
      - name: Status of pm2
        run: pm2 status
      - name: Stop pm2 app
        run: pm2 stop index
      - name: Delete pm2 app
        run: pm2 delete index

